#!/bin/sh
#
# PROVIDE: spectro450
# BEFORE: LOGIN

. /etc/rc.subr

name="spectro450"
desc="Spectro450 appliance"                 
start_cmd="app_start" 
stop_cmd="app_stop" 
rcvar="${name}_enable"
libexec="/usr/local/libexec/${name}"
share="/usr/local/share/${name}"

if [ -e ${libexec}/libapp.sh ] ; then
	. ${libexec}/libapp.sh
else
	exit 1
fi

app_start () 
{
	if [ ! -z $pid ] ; then
		echo "$name is already running."
		return 0
	fi
	if [ -f /firstboot ] ; then
		${libexec}/firstboot
	fi
	if [ -x ${libexec}/${name} ] ; then
		${libexec}/${name} -d
	fi
}

app_stop () 
{
	if [ -z $pid ] ; then
		echo "$name is already stopped."
	else
		kill $pid
		SaveConfig ${name}.conf
	fi
}

load_rc_config $name
run_rc_command "$1"
