#!/bin/sh
#
# This file is part of the Spectro450 Project.
#
# Copyright (c)2020,  Luc Hondareyte
#

[ $# -ne 1 ] && exit 0

libexec="/usr/local/libexec/spectro450"
[ -f ${libexec}/libapp.sh ] && . ${libexec}/libapp.sh || exit 0
[ $JACK = "YES" ] &&  Jack_Register $1
