#!/bin/sh
#
# This file is part of the Spectro450 Project.
#
# Copyright (c)2020,  Luc Hondareyte
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in 
#    the documentation and/or other materials provided with the distribution.   
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

#!/bin/sh
#
app="spectro450"
libexec="/usr/local/libexec/${app}"
share="/usr/local/share/${app}"
fstab="/conf/base/etc/fstab"

if [ $# -ne 2 ] ; then
	exit 0
fi

if [ -f /etc/nanobsd.conf ] ; then
	. /etc/nanobsd.conf
else
	exit 0
fi

if [ -f ${libexec}/libapp.sh ] ; then
	. ${libexec}/libapp.sh
else
	exit 0
fi

Install () {
	dev=$1
	Exec MountUsbDrive $dev
	Exec Toggle_RW
	cd $media
	for p in *pkg
	do
		# Check spectro450 compatibility
		pkg -rF $p | grep spectro450
		if [ $? -eq 0 ] ; then
			Log "installing $p"
			pkg install -y $p
		fi
	done
	cd -
	Exec Toggle_RO
	touch /tmp/pkgmgt.done
	Exec UmountUsbDrive
}

case $1 in 
	'install')
		Log "Installing from $2"
		Install $2
	;;
	'remove')
		Remove $2
	;;
	'update')
		Update $2
	;;
	*)
		exit 1
	;;
esac
