#!/bin/sh
#
# This file is part of the Spectro450 Project.
#
# Copyright (c)2020, Luc Hondareyte
#

libexec="/usr/local/libexec/spectro450"
services="spectro450 jackit"

[ $# -ne 2 ] &&  exit 0
[ -f /etc/nanobsd.conf ] && . /etc/nanobsd.conf || exit 0
[ -f ${libexec}/libapp.sh ] && . ${libexec}/libapp.sh || exit 0

PostInstall () {
	appdir=$1

}

PostRemove () {
	appdir=$1

}

Install () {
	dev=$1
	Exec MountUsbDrive $dev
	Exec Toggle_RW
	cd $media
	#
	# Update services
	for s in $services
	do
		for p in $(ls ${s}*.txz)
		do
			Log "Upgrade $p"
			Exec pkg add $p
			/sbin/service $s restart
			mv $p $p.done
		done
	done
	#
	# Update or install packages
	for p in $(ls *.txz *.pkg)
	do
		Log "Adding $p"
		Exec pkg add $p
		mv $p $p.done
	done
	cd -
	Exec Toggle_RO
	touch /tmp/pkgmgt.done
	Exec UmountUsbDrive
}

Remove () {
	Exec Toggle_RW
	pkg remove -y $1
	mount /cfg
	rm -f /etc/${flatname}.conf \
	      /etc/devd/${flatname}.conf \
              /cfg/${flatname}.conf \
              /cfg/devd/${flatname}.conf
	umount /cfg
	Exec Toggle_RO
}

case $1 in 
	'install')
		Log "Installing from $2"
		Install $2
	;;
	'remove')
		Log "Removing $2"
		Remove $2
	;;
	*)
		exit 1
	;;
esac
