#!/bin/sh
#
SCRIPT=$(basename $0)
LOG="/tmp/${SCRIPT}.log"
rm -f $LOG
ARGS=$*

Exec () {
	$* >> $LOG 2>&1
	rc=$?
	if [ $rc -ne 0 ] ; then
		printf "$1 : command failed! Consult $LOG for details\n"
		exit  $rc
	fi
}

SaveAllFiles () {
	Exec mount /cfg 
	cd /cfg
	find . -type f | while read f
	do
		Exec cp -p /etc/$f .
	done
	sync;sync;sync
	cd && Exec umount /cfg
}

SaveSomeFiles () {
	cd && Exec mount /cfg 
	for f in $ARGS
	do
		if [ -f /etc/$f ] ; then
			cp -p /etc/$f /cfg/$f
		fi
	done
	sync;sync;sync
	Exec umount /cfg 
}

if [ $# -eq 0 ] ; then
	SaveAllFiles
else
	SaveSomeFiles $*
fi 
